# Generated by Django 5.1 on 2024-08-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose_of_visit', models.TextField()),
                ('host', models.CharField(max_length=100)),
                ('id_verified', models.BooleanField(default=False)),
                ('safety_briefing_acknowledged', models.BooleanField(default=False)),
                ('ppe_issued', models.BooleanField(default=False)),
                ('badge_number', models.CharField(blank=True, max_length=50)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
